
# Project Configuration
project:
  name: code_rag
  version: 1.0.0

# Model Configuration
model:
  repo_id: codellama/CodeLlama-7b-hf
  temperature: 0.1
  max_length: 512

# Vector Store Configuration
vector_store:
  path: ./data/vector_store
  collection_name: code_chunks
  chunk_size: 1000
  chunk_overlap: 200

# Paths Configuration
paths:
  codebase: ./data/codebase
  vector_store: ./data/vector_store
